databases:
  - name: laravel-mysql
    databaseName: laravel
    user: laravel

services:
  - type: web
    name: kadriye-portfolio
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: laravel-mysql
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-mysql
          property: password
      - key: LOG_CHANNEL
        value: errorlog
